name: Deploy Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      
      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install & Build
        run: pnpm slidev build

      - name: Deploy to main repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: elvisdragonmao/base-repo
          publish_branch: gh-pages
          publish_dir: ./dist # 或是 ./dist
          destination_dir: ubnparty2026 # 這裡是你想要部署到的子路徑
